[package]

name = "layers"
version = "0.1.0"
authors = ["The Servo Project Developers"]

[dependencies.geom]

git = "https://github.com/servo/rust-geom"

[dependencies.core_foundation]

git = "https://github.com/servo/rust-core-foundation"

[dependencies.io_surface]

git = "https://github.com/servo/rust-io-surface"

[dependencies.xlib]

git = "https://github.com/servo/rust-xlib"

[dependencies.egl]

git = "https://github.com/servo/rust-egl"

[dependencies.glx]

git = "https://github.com/servo/rust-glx"

[dependencies.cgl]

git = "https://github.com/servo/rust-cgl"

[dependencies.gleam]
git = "https://github.com/servo/gleam"

[dependencies.skia]
git = "https://github.com/servo/skia"

[dependencies.azure]
git = "https://github.com/servo/rust-azure"

