[package]

name = "layers"
version = "0.1.0"
authors = ["The Servo Project Developers"]

[dependencies]
libc = "*"
rustc-serialize = "*"
log = "*"

[dependencies.geom]
git = "https://github.com/servo/rust-geom"

[dependencies.gleam]
git = "https://github.com/servo/gleam"

[dependencies.skia]
git = "https://github.com/servo/skia"

[dependencies.azure]
git = "https://github.com/servo/rust-azure"

[target.x86_64-apple-darwin.dependencies.core_foundation]
git = "https://github.com/servo/rust-core-foundation"

[target.x86_64-apple-darwin.dependencies.io_surface]
git = "https://github.com/servo/rust-io-surface"

[target.x86_64-apple-darwin.dependencies.cgl]
git = "https://github.com/servo/rust-cgl"

[target.i686-unknown-linux-gnu.dependencies.glx]
git = "https://github.com/servo/rust-glx"

[target.x86_64-unknown-linux-gnu.dependencies.glx]
git = "https://github.com/servo/rust-glx"

[target.i686-unknown-linux-gnu.dependencies.x11]
version = "1.1.1"
features = ["xlib"]

[target.x86_64-unknown-linux-gnu.dependencies.x11]
version = "1.1.1"
features = ["xlib"]

[target.arm-linux-androideabi.dependencies.egl]
git = "https://github.com/servo/rust-egl"
